import { AIEngine } from '../types';

export const AI_ENGINES: AIEngine[] = [
  // --- IMAGE ENGINES ---
  {
    id: 'mystic',
    name: 'Mystic v2.5',
    provider: 'Magnific',
    type: 'image',
    badge: 'Flagship Freepik/Magnific',
    description: 'El motor insignia de Freepik y Magnific para fotorrealismo extremo, textura de piel y luces cinematográficas.',
    speed: 'Fast',
    quality: '8K Ultra Photoreal',
    maxResolution: '4K Ultra HD',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    features: ['High-Dynamic Range', 'Micro-Textures', 'Lighting Consistency', 'Prompt Adherence'],
    isFlagship: true,
  },
  {
    id: 'flux-pro',
    name: 'Flux 1.1 Pro',
    provider: 'Black Forest Labs',
    type: 'image',
    badge: 'State of the Art',
    description: 'Máxima fidelidad a instrucciones complejas, tipografía legible en la imagen y anatomía perfecta.',
    speed: 'Fast',
    quality: '8K Ultra Photoreal',
    maxResolution: '2K QHD',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    features: ['Complex Prompt Follower', 'Text inside Image', 'Rich Compositions'],
    isFlagship: true,
  },
  {
    id: 'magnific-upscale',
    name: 'Magnific AI Enhancer',
    provider: 'Magnific',
    type: 'image',
    badge: 'Hallucination & Upscale',
    description: 'El revolucionario motor de re-iluminación, aumento de resolución y adición de detalle guiado por prompt.',
    speed: 'Standard',
    quality: 'Hallucination Precision',
    maxResolution: '8K Master',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    features: ['Creativity Slider', 'Detail Hallucination', 'Relighting', 'Texture Regeneration'],
    isFlagship: true,
  },
  {
    id: 'recraft-v3',
    name: 'Recraft V3',
    provider: 'Freepik',
    type: 'image',
    badge: 'Design & Vector',
    description: 'Líder en diseño vectorial, tipografía gráfica, branding, iconos y render 3D limpio.',
    speed: 'Ultra Fast',
    quality: 'Vector & Design',
    maxResolution: '4K Clean',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    features: ['Vector SVG Export', 'Color Palette Control', 'Brand Consistency'],
  },
  {
    id: 'imagen-3',
    name: 'Google Imagen 3',
    provider: 'Google',
    type: 'image',
    badge: 'DeepMind Photoreal',
    description: 'Generador de Google con fidelidad fotográfica de última generación y comprensión contextual profunda.',
    speed: 'Fast',
    quality: '8K Ultra Photoreal',
    maxResolution: '2K QHD',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    features: ['Deep Semantics', 'Artifact Suppression', 'Photographic Nuance'],
  },
  {
    id: 'flux-schnell',
    name: 'Flux Schnell',
    provider: 'Black Forest Labs',
    type: 'image',
    badge: 'Real-time Speed',
    description: 'Generación casi instantánea con excelente fidelidad estética para flujos de iteración rápida.',
    speed: 'Ultra Fast',
    quality: 'High Dynamic',
    maxResolution: '1080p',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3'],
    features: ['Sub-second latency', 'High throughput', 'Concept drafting'],
  },
  {
    id: 'seedream',
    name: 'Seedream',
    provider: 'Freepik',
    type: 'image',
    badge: 'Freepik Classic',
    description: 'Motor ligero y estilizado de Freepik para ilustraciones editoriales y fondos comerciales.',
    speed: 'Ultra Fast',
    quality: 'High Dynamic',
    maxResolution: '2K',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3'],
    features: ['Stock Photo Aesthetics', 'Commercial Art Styles'],
  },

  // --- VIDEO ENGINES ---
  {
    id: 'kling-1-5',
    name: 'Kling 1.5 HD',
    provider: 'Kuaishou',
    type: 'video',
    badge: 'Top Motion Dynamics',
    description: 'Puntero en generación de video con física realista, movimientos complejos de cámara y coherencia temporal.',
    speed: 'Standard',
    quality: 'Pro Cinema',
    maxResolution: '1080p 60fps',
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    features: ['Complex Physics', 'Character Rigging', '5s & 10s Clips', 'Camera Motions'],
    isFlagship: true,
  },
  {
    id: 'minimax-hailuo',
    name: 'MiniMax Hailuo 01',
    provider: 'MiniMax',
    type: 'video',
    badge: 'Cinematic Narrative',
    description: 'Excelente calidad en movimiento humano fluido, planos cinematográficos y expresiones faciales naturales.',
    speed: 'Standard',
    quality: 'Pro Cinema',
    maxResolution: '1080p HD',
    supportedAspectRatios: ['16:9', '9:16'],
    features: ['Human Fluidity', 'Cinematic Pan/Zoom', '6-second scenes'],
    isFlagship: true,
  },
  {
    id: 'runway-gen3',
    name: 'Runway Gen-3 Alpha',
    provider: 'Runway',
    type: 'video',
    badge: 'Director Control',
    description: 'Pionero en video generativo con control estético cinematográfico y movimientos de cámara de Hollywood.',
    speed: 'Cinematic Deep',
    quality: 'Pro Cinema',
    maxResolution: '4K Cinema',
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    features: ['Director Camera Mode', 'Motion Brush', 'Temporal Consistency'],
  },
  {
    id: 'luma-dream',
    name: 'Luma Dream Machine',
    provider: 'Luma',
    type: 'video',
    badge: 'Volumetric Speed',
    description: 'Genera secuencias tridimensionales hiperrealistas con transiciones de luz y paneos envolventes.',
    speed: 'Fast',
    quality: 'Pro Cinema',
    maxResolution: '1080p HD',
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    features: ['3D Camera Trajectories', 'Speed Ramping', 'Volumetric Fog'],
  },
  {
    id: 'cogvideox',
    name: 'CogVideoX Pro',
    provider: 'Freepik',
    type: 'video',
    badge: 'Open Synthesis',
    description: 'Motor de video optimizado en la nube de Freepik para clips dinámicos y loops continuos.',
    speed: 'Fast',
    quality: 'High Dynamic',
    maxResolution: '720p HD',
    supportedAspectRatios: ['16:9', '9:16'],
    features: ['Smooth Interpolation', 'Quick Turnaround', 'Loop Generation'],
  },
];

export const ASPECT_RATIOS: { id: string; label: string; ratio: string; iconClass: string }[] = [
  { id: '1:1', label: '1:1 Cuadrado', ratio: 'aspect-square', iconClass: 'w-4 h-4 border border-current rounded-xs' },
  { id: '16:9', label: '16:9 Paisaje (YouTube/Cine)', ratio: 'aspect-video', iconClass: 'w-5 h-3 border border-current rounded-xs' },
  { id: '9:16', label: '9:16 Retrato (TikTok/Reels)', ratio: 'aspect-[9/16]', iconClass: 'w-3 h-5 border border-current rounded-xs' },
  { id: '4:3', label: '4:3 Clásico', ratio: 'aspect-[4/3]', iconClass: 'w-4 h-3 border border-current rounded-xs' },
  { id: '21:9', label: '21:9 Ultra Panorámico', ratio: 'aspect-[21/9]', iconClass: 'w-6 h-2.5 border border-current rounded-xs' },
];

export const PROMPT_PRESETS = [
  {
    id: 'p-1',
    title: 'Fotografía Editorial 8K (Mystic)',
    type: 'image',
    engine: 'mystic',
    prompt: 'High-end editorial fashion portrait, soft golden hour rim light, 85mm lens f/1.4, hyperrealistic skin pores and natural fabric texture, Hasselblad medium format capture, subtle film grain.',
    category: 'Photoreal',
  },
  {
    id: 'p-2',
    title: 'Cinematic Cyberpunk Drone Shot (Kling 1.5)',
    type: 'video',
    engine: 'kling-1-5',
    prompt: 'Cinematic drone shot flying through a rain-drenched neo-Tokyo street at dusk, holographic signs reflecting in puddles, futuristic hovercars passing by, volumetric steam rising from vents, 4k 60fps.',
    category: 'Cinematic Video',
  },
  {
    id: 'p-3',
    title: 'Magnific Macro Wildlife (Magnific Enhancer)',
    type: 'image',
    engine: 'magnific-upscale',
    prompt: 'Extreme macro shot of an iridescent tropical tree frog resting on a monstera leaf, crystalline water droplets with internal reflections, microscopic details, studio lighting.',
    category: 'Enhancer / Macro',
  },
  {
    id: 'p-4',
    title: 'Brand Vector Illustration (Recraft V3)',
    type: 'image',
    engine: 'recraft-v3',
    prompt: 'Clean vector illustration of a modern creative workspace with dual monitors, potted plants, coffee mug, warm pastel color palette, minimalist geometric lines, dribbble trending style.',
    category: 'Design & Vector',
  },
  {
    id: 'p-5',
    title: 'Slow Motion Ocean Wave (Minimax Hailuo)',
    type: 'video',
    engine: 'minimax-hailuo',
    prompt: 'Cinematic slow-motion 120fps camera moving through the barrel of a translucent turquoise ocean wave at sunset, foam spray catching the warm sunlight, photorealistic fluid dynamics.',
    category: 'Cinematic Video',
  },
];
