import { MagnificEngine } from '../types/magnific';

export const ALL_MAGNIFIC_ENGINES: MagnificEngine[] = [
  // ==========================================
  // 1) GENERACIÓN DE IMÁGENES
  // ==========================================
  {
    id: 'mystic',
    name: 'Mystic',
    category: 'images',
    provider: 'Magnific',
    badge: 'Buque Insignia',
    isFlagship: true,
    description: 'El modelo estrella de Magnific para fotorrealismo extremo, coherencia cromática y micro-texturas sin precedentes.',
    endpoint: '/v1/ai/mystic',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    supportedResolutions: ['1k', '2k', '4k'],
    supportsNegativePrompt: true,
    supportsCreativeDetailing: true,
    supportsHdr: true,
    supportsAdherence: true,
    supportsMultiReference: true,
    maxReferences: 2,
    features: ['Realism Engine', 'HDR Control', 'Adherence Slider', 'Creative Detailing', 'Style & Structure Ref'],
    defaultParams: {
      resolution: '2k',
      aspectRatio: '16:9',
      creativeDetailing: 40,
      hdr: 35,
      adherence: 80,
    },
    creditKey: 'mystic'
  },
  {
    id: 'flux-kontext-pro',
    name: 'Flux Kontext Pro',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'Contexto Profundo',
    description: 'Generación fotorrealista con comprensión profunda del contexto narrativo y soporte de imagen opcional.',
    endpoint: '/v1/ai/text-to-image/flux-kontext-pro',
    optionalInputImage: true,
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Context Guidance', 'Optional Image Guide', 'Anatomy Precision'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'flux-kontext-pro'
  },
  {
    id: 'flux-2-pro',
    name: 'Flux 2 Pro',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'Image-to-Image / Pro',
    description: 'Segunda generación con capacidades completas de síntesis de texto a imagen e imagen a imagen avanzada.',
    endpoint: '/v1/ai/text-to-image/flux-2-pro',
    optionalInputImage: true,
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Pro Composition', 'High Fidelity', 'Advanced Text Rendering'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'flux-2-pro'
  },
  {
    id: 'flux-2-turbo',
    name: 'Flux 2 Turbo',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'Ultra Rápido & Económico',
    description: 'Generación acelerada de bajo costo para borradores inmediatos e iteración conceptual fluida.',
    endpoint: '/v1/ai/text-to-image/flux-2-turbo',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3'],
    supportedResolutions: ['1k'],
    supportsNegativePrompt: false,
    features: ['Low Latency', 'Economic Credits', 'Instant Previews'],
    defaultParams: {
      aspectRatio: '1:1',
      resolution: '1k',
    },
    creditKey: 'flux-2-turbo'
  },
  {
    id: 'flux-2-klein',
    name: 'Flux 2 Klein',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'Hasta 4 Refs',
    description: 'Arquitectura multimodal capaz de combinar hasta 4 imágenes de referencia de personajes, poses o estilos.',
    endpoint: '/v1/ai/text-to-image/flux-2-klein',
    supportsMultiReference: true,
    maxReferences: 4,
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Multi-Ref Fusion', 'Character Consistency', 'Style Blending'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'flux-2-klein'
  },
  {
    id: 'flux-pro-1-1',
    name: 'Flux Pro 1.1',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'SOTA Quality',
    description: 'El estándar de oro en tipografía dentro de la imagen, iluminación natural y comprensión de prompts técnicos.',
    endpoint: '/v1/ai/text-to-image/flux-pro',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['In-Image Typography', 'Complex Geometry', 'Physical Realism'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'flux-pro-1-1'
  },
  {
    id: 'flux-dev',
    name: 'Flux Dev',
    category: 'images',
    provider: 'Black Forest Labs',
    badge: 'Desarrollo Equilibrado',
    description: 'Versión open-weights optimizada por Magnific con gran respuesta dinámica a prompts poéticos o directos.',
    endpoint: '/v1/ai/text-to-image/flux-dev',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3'],
    supportedResolutions: ['1k'],
    supportsNegativePrompt: true,
    features: ['Balanced Speed', 'Predictable Output', 'Creative Latitude'],
    defaultParams: {
      aspectRatio: '1:1',
      resolution: '1k',
    },
    creditKey: 'flux-dev'
  },
  {
    id: 'hyperflux',
    name: 'Hyperflux',
    category: 'images',
    provider: 'Magnific Turbo',
    badge: 'Sub-segundo',
    description: 'Motor de inferencia compilado para tiempos de respuesta ultra-reducidos sin sacrificar nitidez.',
    endpoint: '/v1/ai/text-to-image/hyperflux',
    supportedAspectRatios: ['1:1', '16:9', '9:16'],
    supportedResolutions: ['1k'],
    supportsNegativePrompt: false,
    features: ['Hyper Speed', 'Minimal Latency', 'Draft Mode'],
    defaultParams: {
      aspectRatio: '1:1',
      resolution: '1k',
    },
    creditKey: 'hyperflux'
  },
  {
    id: 'seedream-4',
    name: 'Seedream 4',
    category: 'images',
    provider: 'ByteDance / Seedream',
    badge: 'Ilustración & Editorial',
    description: 'Excelente para arte conceptual, portadas de libros, estética publicitaria y fantasía refinada.',
    endpoint: '/v1/ai/text-to-image/seedream-4',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Fantasy Aesthetics', 'Vibrant Palettes', 'Digital Painting Feel'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '1k',
    },
    creditKey: 'seedream-4'
  },
  {
    id: 'seedream-4-5',
    name: 'Seedream 4.5',
    category: 'images',
    provider: 'ByteDance / Seedream',
    badge: 'Nueva Versión',
    description: 'Última iteración con piel hiper-detallada, iluminación volumétrica y mayor fidelidad a composiciones complejas.',
    endpoint: '/v1/ai/text-to-image/seedream-4-5',
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Volumetric Lighting', 'Refined Textures', 'Cinematic Depth'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'seedream-4-5'
  },
  {
    id: 'seedream-4-5-edit',
    name: 'Seedream 4.5 Edit',
    category: 'images',
    provider: 'ByteDance / Seedream',
    badge: 'Edición Guiada',
    description: 'Edición selectiva de imagen a través de lenguaje natural. Modifica elementos sin alterar la base original.',
    endpoint: '/v1/ai/image-to-image/seedream-edit',
    requiresInputImage: true,
    supportedAspectRatios: ['1:1', '16:9', '9:16', '4:3'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Guided Text Editing', 'Preserves Identity', 'Local Modification'],
    defaultParams: {
      aspectRatio: '1:1',
      resolution: '2k',
    },
    creditKey: 'seedream-4-5-edit'
  },
  {
    id: 'z-image-turbo',
    name: 'Z-Image Turbo',
    category: 'images',
    provider: 'Magnific Labs',
    badge: 'Iteración Veloz',
    description: 'Ideal para sesiones de lluvia de ideas visuales y generación continua en tiempo real.',
    endpoint: '/v1/ai/text-to-image/z-image-turbo',
    supportedAspectRatios: ['1:1', '16:9', '9:16'],
    supportedResolutions: ['1k'],
    features: ['Instant Response', 'Low Resource', 'Fluid Ideation'],
    defaultParams: {
      aspectRatio: '1:1',
      resolution: '1k',
    },
    creditKey: 'z-image-turbo'
  },
  {
    id: 'runway-t2i',
    name: 'RunWay Text-to-Image',
    category: 'images',
    provider: 'Runway',
    badge: 'Cinema Frame',
    description: 'Generación de encuadres fílmicos calibrados para dar continuidad visual a producciones audiovisuales.',
    endpoint: '/v1/ai/text-to-image/runway-gen3',
    supportedAspectRatios: ['16:9', '21:9', '9:16', '1:1'],
    supportedResolutions: ['1k', '2k'],
    supportsNegativePrompt: true,
    features: ['Cinematic Aspect Ratios', 'Director Lens Physics', 'Grading Presets'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'runway-t2i'
  },

  // ==========================================
  // 2) GENERACIÓN DE VIDEO
  // ==========================================
  {
    id: 'kling-2-6-pro',
    name: 'Kling 2.6 Pro',
    category: 'video',
    provider: 'Kuaishou Kling',
    badge: 'Buque Video',
    isFlagship: true,
    description: 'La máxima expresión en video cinemático: física realista de fluidos, ropa y cabello con fidelidad óptica.',
    endpoint: '/v1/ai/text-to-video/kling-v2-6',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    supportsNegativePrompt: true,
    supportsMotionControl: true,
    features: ['Fluid Dynamics', 'Complex Human Motion', '1080p Crystal Clear', 'Prompt Fidelity'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
      resolution: '1080p',
    },
    creditKey: 'kling-2-6-pro'
  },
  {
    id: 'kling-2-6-motion',
    name: 'Kling 2.6 Motion Control',
    category: 'video',
    provider: 'Kuaishou Kling',
    badge: 'Control de Cámara',
    description: 'Permite definir trayectorias precisas de cámara: paneo, inclinación vertical, zoom y movimiento orbital.',
    endpoint: '/v1/ai/text-to-video/kling-motion-control',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    supportsMotionControl: true,
    features: ['3D Camera Paths', 'Orbit & Pan Controls', 'Speed Curves'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
      cameraMovement: 'Pan Right',
    },
    creditKey: 'kling-2-6-motion'
  },
  {
    id: 'kling-2-5-pro',
    name: 'Kling 2.5 Pro',
    category: 'video',
    provider: 'Kuaishou Kling',
    badge: 'Estabilidad Alta',
    description: 'Motor probado y altamente estable para tomas complejas de personas, vehículos y paisajes dinámicos.',
    endpoint: '/v1/ai/text-to-video/kling-v2-5',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    supportsNegativePrompt: true,
    features: ['Rock-solid Temporal Consistency', '1080p Output', 'Natural Lighting'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
      resolution: '1080p',
    },
    creditKey: 'kling-2-5-pro'
  },
  {
    id: 'kling-2-1-pro',
    name: 'Kling 2.1 Pro',
    category: 'video',
    provider: 'Kuaishou Kling',
    badge: 'Clásico & Rápido',
    description: 'Rápido procesamiento para tomas sencillas y planos estáticos con movimiento ambiental.',
    endpoint: '/v1/ai/text-to-video/kling-v2-1',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    supportedDurations: [5],
    features: ['Fast Rendering', 'Good Background Motion'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
      resolution: '720p',
    },
    creditKey: 'kling-2-1-pro'
  },
  {
    id: 'kling-o1',
    name: 'Kling O1 Pro / Standard',
    category: 'video',
    provider: 'Kuaishou Kling',
    badge: 'Prompts Complejos',
    description: 'Optimizado para interpretar instrucciones secuenciales largas y transiciones de escena detalladas.',
    endpoint: '/v1/ai/text-to-video/kling-o1',
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    features: ['Multi-sentence Logic', 'Narrative Sequences'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'kling-o1'
  },
  {
    id: 'minimax-hailuo-02',
    name: 'MiniMax Hailuo 02 1080p',
    category: 'video',
    provider: 'MiniMax',
    badge: 'Expresiones Vivas',
    description: 'El líder en actuación humana, micro-expresiones faciales y movimiento orgánico de personajes.',
    endpoint: '/v1/ai/text-to-video/minimax-hailuo',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    supportsNegativePrompt: true,
    features: ['Facial Emotion Nuance', 'Fluid Body Mechanics', 'Realistic Blinking & Smiles'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
      resolution: '1080p',
    },
    creditKey: 'minimax-hailuo-02'
  },
  {
    id: 'minimax-hailuo-2-3',
    name: 'MiniMax Hailuo 2.3',
    category: 'video',
    provider: 'MiniMax',
    badge: 'Última Versión',
    description: 'Mejora en renderizado de fondos dinámicos, ciudades en movimiento y tomas aéreas cinemáticas.',
    endpoint: '/v1/ai/text-to-video/minimax-hailuo-2-3',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Epic Scale Environments', 'Advanced Drone Shots'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'minimax-hailuo-2-3'
  },
  {
    id: 'minimax-video-01',
    name: 'MiniMax Video-01-Live',
    category: 'video',
    provider: 'MiniMax',
    badge: 'Live Motion',
    description: 'Tomas con sensación de cámara en vivo y movimiento espontáneo de cámara al hombro.',
    endpoint: '/v1/ai/text-to-video/minimax-video-01',
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['720p'],
    supportedDurations: [5],
    features: ['Handheld Cam Vibe', 'Spontaneous Lighting'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'minimax-video-01'
  },
  {
    id: 'wan-2-5-t2v',
    name: 'WAN 2.5 T2V (1080p)',
    category: 'video',
    provider: 'Alibaba WAN',
    badge: 'Texto a Video 1080p',
    description: 'Generación nativa de alta fidelidad desde texto puro con estabilidad geométrica superior.',
    endpoint: '/v1/ai/text-to-video/wan-2-5-t2v',
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Crisp 1080p', 'Sharp Object Contours', 'High Frame Rate Feel'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'wan-2-5-t2v'
  },
  {
    id: 'wan-2-5-i2v',
    name: 'WAN 2.5 I2V (1080p)',
    category: 'video',
    provider: 'Alibaba WAN',
    badge: 'Imagen a Video 1080p',
    description: 'Anima cualquier imagen fija preservando con total fidelidad los rostros, logos y colores del original.',
    endpoint: '/v1/ai/image-to-video/wan-2-5-i2v',
    requiresInputImage: true,
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Perfect Source Adherence', 'Natural Motion Infusion'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'wan-2-5-i2v'
  },
  {
    id: 'wan-2-6',
    name: 'WAN 2.6',
    category: 'video',
    provider: 'Alibaba WAN',
    badge: 'Próxima Generación',
    description: 'Mayor duración de clips y soporte avanzado de partículas y efectos climáticos (lluvia, humo, fuego).',
    endpoint: '/v1/ai/text-to-video/wan-2-6',
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    features: ['Atmospheric FX', 'Extended Coherence'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'wan-2-6'
  },
  {
    id: 'runway-gen4',
    name: 'RunWay Gen4 Turbo',
    category: 'video',
    provider: 'Runway',
    badge: 'Hollywood Grade',
    description: 'El motor predilecto de creadores de cine independiente y publicidad de alta gama.',
    endpoint: '/v1/ai/text-to-video/runway-gen4',
    optionalInputImage: true,
    supportedAspectRatios: ['16:9', '21:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    features: ['Anamorphic Ratios', 'Colorist Grading', 'Directorial Control'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'runway-gen4'
  },
  {
    id: 'runway-act-two',
    name: 'RunWay Act Two',
    category: 'video',
    provider: 'Runway',
    badge: 'Personajes Consistentes',
    description: 'Mantiene la identidad del personaje a través de diferentes planos y condiciones de luz.',
    endpoint: '/v1/ai/text-to-video/runway-act-two',
    requiresInputImage: true,
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Identity Locking', 'Multi-Angle Continuity'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'runway-act-two'
  },
  {
    id: 'ltx-2-0-pro',
    name: 'LTX 2.0 Pro',
    category: 'video',
    provider: 'Lightricks LTX',
    badge: 'Generación Inmediata',
    description: 'Transformación de texto a video con tiempos de generación récord sin perder consistencia temporal.',
    endpoint: '/v1/ai/text-to-video/ltx-video',
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    supportedDurations: [5],
    features: ['Sub-minute Output', 'Lightweight Latent Flow'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'ltx-2-0-pro'
  },
  {
    id: 'seedance-pro',
    name: 'Seedance Pro 1080p',
    category: 'video',
    provider: 'ByteDance',
    badge: 'Coreografía & Danza',
    description: 'Especializado en movimientos corporales rítmicos, acrobacias y coreografías complejas.',
    endpoint: '/v1/ai/text-to-video/seedance-pro',
    supportedAspectRatios: ['9:16', '16:9'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Rhythm Sync', 'Complex Limb Kinematics'],
    defaultParams: {
      aspectRatio: '9:16',
      durationSeconds: 5,
    },
    creditKey: 'seedance-pro'
  },
  {
    id: 'pixverse-v5',
    name: 'PixVerse V5',
    category: 'video',
    provider: 'PixVerse',
    badge: 'Anime & 3D Stylized',
    description: 'Ideal para estética anime, 3D CGI estilizado y mundos de fantasía con iluminación mágica.',
    endpoint: '/v1/ai/text-to-video/pixverse-v5',
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5],
    features: ['Anime Shading', 'Magical Particle Aura'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'pixverse-v5'
  },
  {
    id: 'omnihuman-1-5',
    name: 'OmniHuman 1.5',
    category: 'video',
    provider: 'ByteDance',
    badge: 'Animación Guiada por Audio',
    description: 'Sincroniza los labios y la gesticulación de un retrato humano o avatar con un archivo de audio.',
    endpoint: '/v1/ai/video/omnihuman',
    requiresInputImage: true,
    supportedAspectRatios: ['9:16', '1:1', '16:9'],
    supportedResolutions: ['1080p'],
    supportedDurations: [5, 10],
    features: ['Audio-Lip Sync', 'Natural Head Bobbing', 'Avatar Talking'],
    defaultParams: {
      aspectRatio: '9:16',
      durationSeconds: 5,
    },
    creditKey: 'omnihuman-1-5'
  },
  {
    id: 'vfx-effects',
    name: 'VFX Video Effects',
    category: 'video',
    provider: 'Magnific VFX',
    badge: 'Efectos Especiales',
    description: 'Añade capas de efectos visuales cinematográficos: fuego, desintegración, portales dimensionales y morphing.',
    endpoint: '/v1/ai/video/vfx-effects',
    requiresInputImage: true,
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['1080p'],
    features: ['Particle Disintegration', 'Portal Porting', 'Superpowers Glow'],
    defaultParams: {
      aspectRatio: '16:9',
      durationSeconds: 5,
    },
    creditKey: 'vfx-effects'
  },

  // ==========================================
  // 3) EDICIÓN DE IMAGEN
  // ==========================================
  {
    id: 'upscaler-creative',
    name: 'Upscaler Creative',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Alucinación Creativa',
    isFlagship: true,
    description: 'El célebre upscaler de Magnific que reinventa y añade detalle fotorrealista milimétrico guiado por prompt.',
    endpoint: '/v1/ai/image-upscaler/creative',
    requiresInputImage: true,
    supportedResolutions: ['2k', '4k', '8k'],
    supportsCreativeDetailing: true,
    supportsHdr: true,
    supportsScaleFactor: true,
    features: ['Creativity Slider', 'Micro-Detail Hallucination', 'HDR Enhancer', 'Up to 8K Master'],
    defaultParams: {
      resolution: '4k',
      scaleFactor: 4,
      creativeDetailing: 60,
      hdr: 40,
    },
    creditKey: 'upscaler-creative'
  },
  {
    id: 'upscaler-precision',
    name: 'Upscaler Precision',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Fidelidad Máxima',
    description: 'Aumenta la resolución preservando exactamente las líneas, textos y rasgos originales sin inventar detalles.',
    endpoint: '/v1/ai/image-upscaler/precision',
    requiresInputImage: true,
    supportedResolutions: ['2k', '4k', '8k'],
    supportsScaleFactor: true,
    features: ['Zero Artifact Hallucination', 'Exact Typography Sharpness', 'Faithful Restoration'],
    defaultParams: {
      resolution: '2k',
      scaleFactor: 2,
    },
    creditKey: 'upscaler-precision'
  },
  {
    id: 'relight',
    name: 'Relight',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Iluminación Nueva',
    description: 'Transforma por completo la dirección, color e intensidad de la luz (hora dorada, neón cyberpunk, luz de vela).',
    endpoint: '/v1/ai/image-editing/relight',
    requiresInputImage: true,
    supportedResolutions: ['2k'],
    features: ['Dynamic Shadow Casting', 'Ambient Shift', 'Color Temperature Control'],
    defaultParams: {
      resolution: '2k',
    },
    creditKey: 'relight'
  },
  {
    id: 'style-transfer',
    name: 'Style Transfer',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Transferencia Artística',
    description: 'Aplica el estilo artístico, pincelada o iluminación de una imagen de referencia a tu imagen base.',
    endpoint: '/v1/ai/image-editing/style-transfer',
    requiresInputImage: true,
    supportsMultiReference: true,
    maxReferences: 1,
    supportedResolutions: ['2k'],
    features: ['Texture Mapping', 'Artistic Medium Emulation', 'Palette Inheritance'],
    defaultParams: {
      resolution: '2k',
    },
    creditKey: 'style-transfer'
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Recorte de Precisión',
    description: 'Extracción instantánea de fondo con detección perfecta de cabello fino, transparencias y bordes complejos.',
    endpoint: '/v1/ai/image-editing/remove-background',
    requiresInputImage: true,
    supportedResolutions: ['2k'],
    features: ['Alpha Channel PNG', 'Hair & Fur Detection', 'Transparent Backdrop'],
    defaultParams: {
      resolution: '2k',
    },
    creditKey: 'remove-background'
  },
  {
    id: 'image-expand',
    name: 'Image Expand (Outpainting)',
    category: 'editing',
    provider: 'Magnific',
    badge: 'Outpainting Guiado',
    description: 'Expande los bordes de tu imagen hacia cualquier formato (de vertical a panorámico) manteniendo la continuidad perfecta.',
    endpoint: '/v1/ai/image-editing/image-expand',
    requiresInputImage: true,
    supportedAspectRatios: ['16:9', '21:9', '1:1', '9:16'],
    supportedResolutions: ['2k', '4k'],
    features: ['Canvas Extension', 'Environment Continuity', 'Composition Balancing'],
    defaultParams: {
      aspectRatio: '16:9',
      resolution: '2k',
    },
    creditKey: 'image-expand'
  },

  // ==========================================
  // 4) AUDIO
  // ==========================================
  {
    id: 'music-elevenlabs',
    name: 'Music Generation (ElevenLabs)',
    category: 'audio',
    provider: 'ElevenLabs / Magnific',
    badge: 'Música desde Texto',
    isFlagship: true,
    description: 'Genera pistas instrumentales y canciones completas en cualquier género musical, tempo e instrumentación.',
    endpoint: '/v1/ai/audio/music',
    supportedDurations: [30, 60],
    supportsAudioGenre: true,
    features: ['Studio Master Quality', 'Multi-Instrument Arrangement', 'Genre & Mood Tuning'],
    defaultParams: {
      durationSeconds: 30,
      genre: 'Cinematic Epic Orchestral',
      tempo: 'Medium',
    },
    creditKey: 'music-elevenlabs'
  },
  {
    id: 'sound-effects',
    name: 'Sound Effects (SFX)',
    category: 'audio',
    provider: 'Magnific Sound',
    badge: 'Efectos de Sonido',
    description: 'Diseña efectos de sonido foley y cinemáticos: explosiones, pasos en la nieve, interfaz sci-fi o lluvia.',
    endpoint: '/v1/ai/audio/sound-effects',
    supportedDurations: [5, 10],
    features: ['Stereo Spatial Sound', 'High Sample Rate', 'Foley Realism'],
    defaultParams: {
      durationSeconds: 5,
    },
    creditKey: 'sound-effects'
  },
  {
    id: 'audio-isolation',
    name: 'Audio Isolation (SAM Audio)',
    category: 'audio',
    provider: 'Meta SAM Audio',
    badge: 'Aislamiento de Pistas',
    description: 'Aísla la voz, batería, bajo o elimina el ruido ambiental de cualquier archivo de audio o video.',
    endpoint: '/v1/ai/audio/isolation',
    supportedDurations: [30],
    features: ['Vocal Stem Extraction', 'Noise Cancellation', 'Lossless Separation'],
    defaultParams: {
      durationSeconds: 30,
    },
    creditKey: 'audio-isolation'
  }
];

export function getEngineById(id: string): MagnificEngine | undefined {
  return ALL_MAGNIFIC_ENGINES.find(e => e.id === id);
}

export function getEnginesByCategory(category: string): MagnificEngine[] {
  return ALL_MAGNIFIC_ENGINES.filter(e => e.category === category);
}

export const ENGINES_BY_CATEGORY: Record<string, MagnificEngine[]> = {
  images: ALL_MAGNIFIC_ENGINES.filter(e => e.category === 'images'),
  video: ALL_MAGNIFIC_ENGINES.filter(e => e.category === 'video'),
  editing: ALL_MAGNIFIC_ENGINES.filter(e => e.category === 'editing'),
  audio: ALL_MAGNIFIC_ENGINES.filter(e => e.category === 'audio'),
};

export const CATEGORY_META: Record<string, { title: string; desc: string }> = {
  images: {
    title: 'Imágenes',
    desc: 'Generación con Mystic, Flux 2, Seedream y modelos de alta resolución.',
  },
  video: {
    title: 'Video Cinemático',
    desc: 'Kling 2.6, MiniMax Hailuo, Wan 2.6 y Runway Gen-4.',
  },
  editing: {
    title: 'Edición y Upscale',
    desc: 'Magnific Upscaler 2.0 (Creative & Precision), Relight y Transferencia.',
  },
  audio: {
    title: 'Audio & Foley',
    desc: 'Síntesis musical ElevenLabs, efectos de sonido y aislamiento.',
  },
};

